services:
  bedrockconnect:
    container_name: bedrock_connect
    image: chadly/bedrockconnect:latest
    build:
      context: bedrockconnect
    restart: unless-stopped
    ports:
      - "19132:19132/udp"

  router:
    container_name: minecraft_router
    image: itzg/mc-router
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      MAPPING: __ROUTER_MAPPING__
