services:
  bedrockconnect:
    container_name: bedrock_connect
    build:
      context: bedrockconnect
    restart: unless-stopped
    ports:
      - "19132:19132/udp"

  router:
    container_name: minecraft_router
    image: itzg/mc-router
    restart: unless-stopped
    environment:
      MAPPING: |
        vanilla.minecraft.lan=vanilla:25565
        hogwarts.minecraft.lan=hogwarts:25565
        minecity.minecraft.lan=minecity:25565
        unknown_host.minecraft.lan=unknown_host:25565
        winter.minecraft.lan=winter:25565
    ports:
      - "25565:25565"
