services:
  bedrockconnect:
    container_name: bedrock_connect
    image: chadly/bedrockconnect:latest
    build:
      context: bedrockconnect
    restart: unless-stopped
    ports:
      - "19132:19132/udp"
